/*
 * 定义类型常量
*/
const PRODUCT_DETAIL_SHOW = 'PRODUCT_DETAIL_SHOW'
const PRODUCT_DETAIL_HIDE = 'PRODUCT_DETAIL_HIDE'
const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
const GET_SLIDER = 'GET_SLIDER'
const SHOW_ALERT = 'SHOW_ALERT'
const ALERT_MSG = 'ALERT_MSG'

export default {
	PRODUCT_DETAIL_SHOW,
	PRODUCT_DETAIL_HIDE,
	GET_PRODUCT_LIST,
	GET_SLIDER,
	SHOW_ALERT,
	ALERT_MSG
}